### ISSUE TITLE
Different stack and blind sizes

### ISSUE THREAD

**Issue by PhDtimothy** [happypepper/DeepHoldem#10]
Hello, To start off I think this a great project and well developed and commented so thank you. 
I am writing a paper about poker myself and the code here is giving me a lot of ideas. 

This and the official deepstack are both trained on one stack size (20000) and one blind size. The deepstack team used their bot to also play with different stack sizes and different blind sizes like in regular poker matches without retraining their model. However they have not given clear instructions how they exactly did this.
So I was wondering if you had any ideas how to implement this in DeepHoldem without retraining it for different stack and blind sizes. 
My bad solution to this was to just bet proportionally to the original model, so a raise of 300 with a stack size 20000 ends up as a raise of 150 with a stack size of only 10000. This is not a very clean solution and I wonder how the official deepstack did it. 
Thanks for any suggestions

**Comment by happypepper** [comment]
I think the bad solution you mentioned is actually a good solution.
Because the models are trained with lots of varying pot sizes, it can handle any stack size between 1bb and 200bb. If you scale the pot and stack so that stack = 20000 chips, then you can input the situation into the model, as you said.

I don't know how deepstack did it, but I think they will use this method too.

**Comment by PhDtimothy** [comment]
Ah that's great. Thank you, that makes a lot of sense. I agree with you, deepstack said they did not retrain their models. So there really is not another way of doing it other than the way you described.

@happypepper This is a bit offtopic but I am really interested what projects you are currently working on. Obviously you dont have to say if you dont want to. Id also be interested in your plans for future poker projects. I personally think 6 man / 9 man poker would be really challenging and interesting.

**Comment by Jedrickbender** [comment]
@PhDtimothy and @happypepper I was wondering how exactly one would implement this in code. I have changed the code so I can simply input the current matchstate as a string into deepstack.lua and it outputs its action. But I am not exactly sure how I can change the blind size properly after a hand. Would it be enough to change the arguments.bb and arguments.sb size after a hand is played, so that deepstack.lua solves for the new blind sizes? Thank you many times for your help.

**Comment by aikupoker** [comment]
Hey @Jedrickbender , did you be able to resolve it? I want to test dynamically different stacks and I'm having issues
