### ISSUE TITLE
What is to be expected from this project?

### ISSUE THREAD

**Issue by Dunge** [happypepper/DeepHoldem#44]
After searching for a while, this is the project that seems to be the most promising in term of publicly available no limit hold'em advanced machine learning based bot with a full 52cards deck fast enough for real time decisions.

Now I believe most neophytes  like me stumbling on this repo all ask themselves this shameful question: "can I make money out of this?". Other than being prohibited by the terms and conditions, is it in the realm of possibilities to think we could set up the bot to play against real opponents online in real poker softwares or is it a ridiculous assumption?

I'm actually surprised this isn't something more mainstream. If the technology exists, what is preventing everybody use it and completely render online poker obsolete?

At a quick glance, the project "dealer" script generate the board flop and the bot play on it, there's no easy way to feed in a board and player information coming from an external source. But I guess it wouldn't be too hard to create a script doing that using the existing functions.

There's also the fact that this project is not straightforward to use at all. I consider myself pretty knowledgeable in programming and Linux usage, and I just spent the last 5 hours trying to make this run on WLS2 without success, just configuring Cuda for it is a mess, not to mention this project reliance on cutorch 1.0 makes it dependent on Cuda max 9.2 if I understand correctly which is already quite dated. The there's the whole model training thing that isn't straightforward either. So before putting more effort into it, I decided to just gonna go ahead and ask this here. I'm also going to ask if anyone know other projects that are still actively updated or if I am on the right track with this one?

**Comment by lucky72s** [comment]
I was also frustrated with the software used in this project, that's why I converted it to Python and PyTorch and named it creatively [DyypHoldem](https://github.com/lucky72s/dyypholdem).

It is cross-platform and runs natively on Linux and Windows. Together with a modern GPU it also runs fairly quickly.

It includes the option to play against either manually or let it play against the famous [Slumbot](https://www.slumbot.com/). It can certainly be adapted to play against other bots or online, but not sure about any success rates :-) ...

**Comment by Dunge** [comment]
Thanks! I think I'll try your implementation, should be easier to get things working that fiddling with a Linux subsystem and versioning issues.
